name: Test GitHub Action
on: [pull_request]

jobs:
  run:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v2

    - name: Check spelling of repository
      uses: crate-ci/typos@master
      with: 
        files: 

    # - name: Use custom config file
    #   uses: crate-ci/typos@master
    #   with: 
    #     files: 
    #     config: ./myconfig.toml

    # - name: Ignore implicit configuration file
    #   uses: crate-ci/typos@master
    #   with: 
    #     files: 
    #     isolated: true
